services:
  redis:
    image: redis:alpine
    platform: linux/amd64
    ports:
      - "6379:6379"

  django:
    build: .
    platform: linux/amd64
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

  celery:
    build: .
    platform: linux/amd64
    command: celery -A cp360 worker -l info
    volumes:
      - .:/app
    depends_on:
      - redis
      - django
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0 