# Generated by Django 5.2.4 on 2025-07-30 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='processing_status',
            field=models.CharField(choices=[('UPLOADING', 'Uploading'), ('PROCESSING', 'Processing'), ('READY', 'Ready'), ('FAILED', 'Failed')], default='UPLOADING', max_length=12),
        ),
        migrations.AddField(
            model_name='product',
            name='temporary_video',
            field=models.FileField(blank=True, null=True, upload_to='temp_videos/'),
        ),
    ]
