# Generated by Django 5.2.4 on 2025-07-30 13:58

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_processing_status_product_temporary_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='video',
            field=models.FileField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='videos/'),
        ),
    ]
